version: "3.7"

services:
  ui:
    build: .
    container_name: alcatraz_ui
    command: sh -c "yarn dev"
    volumes:
      - .:/ui
      - node_modules:/ui/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules:
